---
# ydbd static node deployment

- name: Create the YDB audit base directory
  file:
    state: directory
    path: "{{ ydb_dir }}/audit"
    group: ydb
    owner: ydb
    mode: '0700'

- name: Create the YDB audit directory for the storage node
  file:
    state: directory
    path: "{{ ydb_dir }}/audit/storage"
    group: ydb
    owner: ydb
    mode: '0700'

- name: Add the static node startup wait script
  template:
    src: wait_initial.j2
    dest: "{{ ydb_dir }}/home/wait_initial.sh"
    group: ydb
    owner: ydb
    mode: '0755'

- name: Add the storage recovery wait script
  template:
    src: wait_normal.j2
    dest: "{{ ydb_dir }}/home/wait_normal.sh"
    group: ydb
    owner: ydb
    mode: '0755'

- name: Generate the static node service files
  template:
    src: static-service.j2
    dest: "/etc/systemd/system/ydbd-storage.service"
    group: root
    owner: root
    mode: '0644'

- name: Refresh systemd services configuration
  ansible.builtin.systemd:
    daemon_reload: true
