---
# unified agent installation

- name: Create the unified agent base directory
  file: state=directory path={{ unified_agent_home }} group=bin owner=root mode='755'

- name: Create the unified agent storage directory
  file: state=directory path={{ unified_agent_home }}/storage group=ydb owner=ydb mode='700'

- name: Create the technical logs directory
  file: state=directory path={{ ydb_dir }}/logs group=ydb owner=ydb mode='750'

- name: Copy the unified agent binary
  copy: src={{ unified_agent_binary }} dest={{ unified_agent_home }}/unified_agent group=bin owner=root mode='555'

- name: Generate the unified agent service files
  template:
    src: unified-agent-service.j2
    dest: "/etc/systemd/system/ydb-unified-agent.service"

- name: Generate the unified agent configuration
  template:
    src: unified-agent-config.j2
    dest: "{{ unified_agent_home }}/unified_agent.yaml"

- name: Generate the log rotation configuration
  template:
    src: ydb-logs-rotation.j2
    dest: /etc/logrotate.d/ydbd

- name: Refresh systemd services configuration
  ansible.builtin.systemd:
    daemon_reload: true

- name: Activate the unified agent
  ansible.builtin.systemd:
    enabled: true
    state: restarted
    name: ydb-unified-agent
