---
# YDB single static node restart tasks

- name: restart the storage node at {{ snode_name }}
  ansible.builtin.systemd:
    state: restarted
    name: ydbd-storage
  delegate_to: "{{ snode_name }}"
  delegate_facts: true
  any_errors_fatal: true

- name: wait for ydb discovery to start working locally
  ydb_platform.ydb.wait_discovery:
    ydb_bin: "{{ ydb_dir }}/bin/ydb"
    ld_library_path: "{{ ydb_dir }}/lib"
    ca_file: "{{ ydb_dir }}/certs/ca.crt"
    endpoint: "grpcs://{{ inventory_hostname }}:2135"
    database: "/{{ ydb_domain }}"
    token: "{{ ydb_credentials.token }}"
  delegate_to: "{{ snode_name }}"
  delegate_facts: true
  any_errors_fatal: true

- name: wait for ydb healthcheck switch to "GOOD" status
  ydb_platform.ydb.wait_healthcheck:
    ydb_bin: "{{ ydb_dir }}/bin/ydb"
    ld_library_path: "{{ ydb_dir }}/lib"
    ca_file: "{{ ydb_dir }}/certs/ca.crt"
    endpoint: "grpcs://{{ inventory_hostname }}:2135"
    database: "/{{ ydb_domain }}"
    token: "{{ ydb_credentials.token }}"
  run_once: true
