---
# YDB single static node restart tasks

- name: Restart the storage node at {{ snode_name }}
  ansible.builtin.systemd:
    state: restarted
    name: ydbd-storage
  delegate_to: "{{ snode_name }}"
  delegate_facts: true
  any_errors_fatal: true

- name: Transfer the secrets
  copy: src=secret dest={{ ydb_dir }}/certs/secret
  delegate_to: "{{ snode_name }}"
  delegate_facts: true
  any_errors_fatal: true

- name: Wait for storage state recovery on {{ snode_name }}
  command: "sudo -u ydb {{ ydb_dir }}/home/wait_normal.sh {{ inventory_hostname }}"
  delegate_to: "{{ snode_name }}"
  delegate_facts: true
  any_errors_fatal: true

- name: Cleanup the transferred secrets
  file: state=absent path={{ ydb_dir }}/certs/secret
  delegate_to: "{{ snode_name }}"
  delegate_facts: true
