- name: check if fq-connector-go present
  stat:
    path: "{{ ydb_fq_connector_dir }}/bin/{{ ydb_fq_connector_executable }}"
  register: ydb_fq_connector_stat

- name: copy fq-connector-go binary file
  copy:
    src: "{{ ydb_fq_connector_binary }}"
    dest: "{{ ydb_fq_connector_dir }}/bin/{{ ydb_fq_connector_executable }}"
    attributes: +x
    mode: 0755
  when: not ydb_fq_connector_stat.stat.exists or ydb_fq_connector_binary_force_install
