- name: create YDB bin directory
  file:
    path: "{{ ydb_dir }}/bin"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy YDB server binary file
  copy:
    src: "{{ ydbd_binary }}"
    dest: "{{ ydb_dir }}/bin/ydbd"
    attributes: +x
    mode: 0755
    follow: true

- name: copy YDB cli binary file
  copy:
    src: "{{ ydb_cli_binary }}"
    dest: "{{ ydb_dir }}/bin/ydb"
    attributes: +x
    mode: 0755
    follow: true
