---
# ydbd storage initialization

- name: Add the disk formatting script
  template:
    src: safe_format.j2
    dest: "{{ ydb_dir }}/home/safe_format.sh"
    group: ydb
    owner: ydb
    mode: '0755'

- name: Execute disk formatting
  command: "{{ ydb_dir }}/home/safe_format.sh {{ item['name'] }} {{ item['label'] }}"
  with_items: "{{ ydb_disks }}"

- name: Start the storage nodes
  ansible.builtin.systemd:
    state: started
    name: ydbd-storage
  any_errors_fatal: true

- name: Transfer the secrets
  copy:
    src: secret
    dest: "{{ ydb_dir }}/certs/secret"
    group: ydb
    owner: ydb
    mode: '0700'
  when: ydb_cluster_extension is defined

- name: Wait for storage node startup
  command: "{{ ydb_dir }}/home/wait_initial.sh {{ inventory_hostname }}"
  become: true
  become_user: ydb
  any_errors_fatal: true

- name: Initial YDB cluster setup
  block:
    - name: Add the storage initialization script
      template:
        src: init_storage.j2
        dest: "{{ ydb_dir }}/home/init_storage.sh"
        group: ydb
        owner: ydb
        mode: '0755'
    - name: Add the password initialization script
      template:
        src: init_password.j2
        dest: "{{ ydb_dir }}/home/init_password.sh"
        group: ydb
        owner: ydb
        mode: '0755'
      when: ydb_cluster_extension is undefined
    - name: Initialize the YDB storage
      command: "{{ ydb_dir }}/home/init_storage.sh {{ inventory_hostname }}"
      become: true
      become_user: ydb
    - name: Wait for storage bootstrap to complete
      command: "{{ ydb_dir }}/home/wait_normal.sh {{ inventory_hostname }}"
      become: true
      become_user: ydb
    - name: Transfer the secrets
      copy:
        src: secret
        dest: "{{ ydb_dir }}/certs/secret"
        group: ydb
        owner: ydb
        mode: '0700'
      when: ydb_cluster_extension is undefined
    - name: Set the initial cluster password
      command: "{{ ydb_dir }}/home/init_password.sh {{ inventory_hostname }}"
      become: true
      become_user: ydb
      when: ydb_cluster_extension is undefined
  run_once: true

- name: Cleanup the transferred secrets
  file: state=absent path={{ ydb_dir }}/certs/secret

- name: Enable the storage nodes for automatic startup
  ansible.builtin.systemd:
    enabled: true
    name: ydbd-storage
