{
 "title": "CPU",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU by execution pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by (execpool) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{execpool}}"
    }
   ]
  },
  {
   "title": "Actor count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (activity) (utils_ActorsAliveByActivity{database=\"$database\",container=\"ydb-dynamic\"})",
     "legendFormat": "{{activity}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "User pool - CPU by actors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (activity) (rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",execpool=\"User\"}[$__rate_interval]))",
       "legendFormat": "{{activity}}"
      }
     ]
    },
    {
     "title": "User pool - CPU by host",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (host, pod) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\",execpool=\"User\"}[$__rate_interval]))",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    },
    {
     "title": "System pool - CPU by actors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (activity) (rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",execpool=\"System\"}[$__rate_interval]))",
       "legendFormat": "{{activity}}"
      }
     ]
    },
    {
     "title": "System pool - CPU by host",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (host, pod) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\",execpool=\"System\"}[$__rate_interval]))",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    },
    {
     "title": "Batch pool - CPU by actors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (activity) (rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",execpool=\"Batch\"}[$__rate_interval]))",
       "legendFormat": "{{activity}}"
      }
     ]
    },
    {
     "title": "Batch pool - CPU by host",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (host, pod) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\",execpool=\"Batch\"}[$__rate_interval]))",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    },
    {
     "title": "IC pool - CPU by actors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (activity) (rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IC\"}[$__rate_interval]))",
       "legendFormat": "{{activity}}"
      }
     ]
    },
    {
     "title": "IC pool - CPU by host",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (host, pod) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IC\"}[$__rate_interval]))",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    },
    {
     "title": "IO pool - CPU by actors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (activity) (rate(utils_ElapsedMicrosecByActivity{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IO\"}[$__rate_interval]))",
       "legendFormat": "{{activity}}"
      }
     ]
    },
    {
     "title": "IO pool - CPU by host",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (host, pod) (rate(utils_ElapsedMicrosec{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IO\"}[$__rate_interval]))",
       "legendFormat": "{{host}}{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "User pool - event processing",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingCountUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"User\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "User pool - event processing time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"User\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "User pool - event delivery",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventDeliveryTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"User\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "User pool - activation",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_ActivationTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"User\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "System pool - event processing",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingCountUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"System\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "System pool - event processing time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"System\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "System pool - event delivery",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventDeliveryTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"System\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "System pool - activation",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_ActivationTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"System\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Batch pool - event processing",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingCountUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"Batch\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Batch pool - event processing time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"Batch\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Batch pool - event delivery",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventDeliveryTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"Batch\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Batch pool - activation",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_ActivationTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"Batch\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "IC pool - event processing",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingCountUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IC\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "IC pool - event processing time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IC\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "IC pool - event delivery",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventDeliveryTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IC\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "IC pool - activation",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_ActivationTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IC\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "IO pool - event processing",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingCountUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IO\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "IO pool - event processing time",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventProcessingTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IO\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "IO pool - event delivery",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_EventDeliveryTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IO\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "IO pool - activation",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (le) (rate(utils_ActivationTimeUs_bucket{database=\"$database\",container=\"ydb-dynamic\",execpool=\"IO\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}