{
 "title": "DataShard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RowRead rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_EngineHostRowReads{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "RowRead bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_EngineHostRowReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "RangeRead rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_EngineHostRangeReadRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "RangeRead bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_EngineHostRangeReadBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "RowRead rows per request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (le) (rate(tablets_DataShard_SelectRowsPerRequest_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RangeRead rows per request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (le) (rate(tablets_DataShard_RangeReadRowsPerRequest_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RowUpdate rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_EngineHostRowUpdates{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "RowUpdate bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_EngineHostRowUpdateBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "RowErase rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_EngineHostRowErases{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "RowErase bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_EngineHostRowEraseBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "BulkUpsert rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_UploadRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "BulkUpsert bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_UploadRowsBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Scanned rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_ScannedRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "Scanned bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_ScannedBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "ReadColumns rows",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_ReadColumnsRows{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "rows"
    }
   ]
  },
  {
   "title": "ReadColumns bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum (rate(tablets_DataShard_ReadColumnsBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+_ReadBytes\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)_ReadBytes\")[$__rate_interval:]))",
       "legendFormat": "{{name_label}}"
      }
     ]
    },
    {
     "title": "Written bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+_WrittenBytes\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)_WrittenBytes\")[$__rate_interval:]))",
       "legendFormat": "{{name_label}}"
      }
     ]
    },
    {
     "title": "Loaded blocks",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+_LoadedBlocks\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)_LoadedBlocks\")[$__rate_interval:]))",
       "legendFormat": "{{name_label}}"
      }
     ]
    },
    {
     "title": "Touched blocks",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"tablets_DataShard_.+_TouchedBlocks\"}, \"name_label\", \"$1\", \"__name__\", \"tablets_DataShard_(.+)_TouchedBlocks\")[$__rate_interval:]))",
       "legendFormat": "{{name_label}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prepare execute latency(us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_DataShard_PrepareExecLatency_bucket{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Prepare complete latency(us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_DataShard_PrepareSuccessCompleteLatency_bucket{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Progress execute latency(us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_DataShard_TxProgressExecLatency_bucket{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Progress complete latency(us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_DataShard_TxProgressCompleteLatency_bucket{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "AcceptedPlanStep complete latency(us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_DataShard_AcceptedPlanStepCompleteLatency_bucket{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "PlanToExecute latency(us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_DataShard_PlanToExecuteLatency_bucket{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tablet latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "RO latency (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_TxRoLatency_bucket{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RW latency (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_TxRwLatency_bucket{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Commit latency (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (le) (rate(tablets_TxCommitLatency_bucket{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compaction bytes read",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum (rate(tablets_CompactionBytesRead{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "Compaction bytes written",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum (rate(tablets_CompactionBytesWritten{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "Compaction queue sizes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen0\"})",
       "legendFormat": "gen0"
      },
      {
       "expr": "sum(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen1\"})",
       "legendFormat": "gen1"
      },
      {
       "expr": "sum(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen2\"})",
       "legendFormat": "gen2"
      },
      {
       "expr": "sum(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen3\"})",
       "legendFormat": "gen3"
      }
     ]
    },
    {
     "title": "Compactions in fly",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(tablets_InFlyTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen0\"})",
       "legendFormat": "gen0"
      },
      {
       "expr": "sum(tablets_InFlyTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen1\"})",
       "legendFormat": "gen1"
      },
      {
       "expr": "sum(tablets_InFlyTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen2\"})",
       "legendFormat": "gen2"
      },
      {
       "expr": "sum(tablets_InFlyTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen3\"})",
       "legendFormat": "gen3"
      }
     ]
    },
    {
     "title": "Compactions finished",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(rate(tablets_FinishedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen0\"}[$__rate_interval]))",
       "legendFormat": "gen0"
      },
      {
       "expr": "sum(rate(tablets_FinishedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen1\"}[$__rate_interval]))",
       "legendFormat": "gen1"
      },
      {
       "expr": "sum(rate(tablets_FinishedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen2\"}[$__rate_interval]))",
       "legendFormat": "gen2"
      },
      {
       "expr": "sum(rate(tablets_EnqueuedTasks{database=\"$database\",container=\"ydb-dynamic\",task=\"compaction_gen3\"}[$__rate_interval]))",
       "legendFormat": "gen3"
      }
     ]
    }
   ]
  },
  {
   "title": "Readsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Readset received count",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_ReadsetReceivedCount{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Readset received size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_ReadsetReceivedSize{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "Readset sent count",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_ReadsetSentCount{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Readset sent size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_ReadsetSentSize{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "MiniKQL program size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum (rate(tablets_DataShard_MiniKQLProgramSize{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "Result size",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_TxResultSize{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    },
    {
     "title": "Acks sent",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_AckSent{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Acks sent delayed",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DataShard_AckSentDelayed{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "max TxCompleteLag",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "max(tablets_MAX_DataShard_TxCompleteLag_{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "max ScanTxCompleteLag",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "max(tablets_MAX_DataShard_ScanTxCompleteLag_{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "ImmediateTxInFly",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(tablets_SUM_DataShard_ImmediateTxInFly_{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Redo written bytes",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum(rate(tablets_DbRedoWrittenBytes{database=\"$database\",container=\"ydb-dynamic\",type=\"DataShard\"}[$__rate_interval]))",
       "legendFormat": "bytes"
      }
     ]
    }
   ]
  }
 ]
}