{
 "title": "Query engine",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kqp_Requests_QueryExecute{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Execute"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryExecPrepared{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "ExecPrepared"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryPrepare{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Prepare"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryExplain{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Explain"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryValidate{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Validate"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryParse{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Parse"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryBeginTx{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "BeginTx"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryCommitTx{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "CommitTx"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryRollbackTx{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "RollbackTx"
    },
    {
     "expr": "sum(rate(kqp_Requests_CreateSession{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "CreateSession"
    },
    {
     "expr": "sum(rate(kqp_Requests_PingSession{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "PingSession"
    },
    {
     "expr": "sum(rate(kqp_Requests_CloseSession{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "CloseSession"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryOther{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Request bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kqp_Requests_Bytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(kqp_Requests_ParametersBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "parameters"
    },
    {
     "expr": "sum(rate(kqp_Requests_QueryBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "query"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (name_label) (rate(label_replace({database=\"$database\",container=\"ydb-dynamic\",__name__=~\"kqp_YdbResponses_.+\"}, \"name_label\", \"$1\", \"__name__\", \"kqp_YdbResponses_(.+)\")[$__rate_interval:]))",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Response bytes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(kqp_Responses_Bytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(kqp_Responses_QueryResultBytes{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "query result"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queries per session",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Workers_QueriesPerWorkerQ_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Active sessions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(kqp_Workers_Active{database=\"$database\",container=\"ydb-dynamic\"})",
       "legendFormat": "workers"
      }
     ]
    },
    {
     "title": "Session lifespan (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Workers_LifeSpanMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Sessions",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(rate(kqp_Workers_Created{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "created"
      },
      {
       "expr": "sum(rate(kqp_Workers_ClosedIdle{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "closed as idle"
      },
      {
       "expr": "sum(rate(kqp_Workers_ClosedError{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "closed on error"
      },
      {
       "expr": "sum(rate(kqp_Workers_ClosedRequest{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "closed by request"
      }
     ]
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Execute latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Query_ExecuteLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "BeginTx latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Query_BeginTxLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "ExecPrepared latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Query_ExecPreparedLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "CommitTx latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Query_CommitTxLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Prepare latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Query_PrepareLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "RollbackTx latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Query_RollbackTxLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Explain latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Query_ExplainLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Validate latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "sum by (le) (rate(kqp_Query_ValidateLatencyMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}