{
 "title": "TxProxy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database", "query": { "query": "label_values(database)" } },
   { "name": "ds", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(proxy_Navigate_Request{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Navigate Request"
    },
    {
     "expr": "sum(rate(proxy_Propose_MakeRequest{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Make Request"
    },
    {
     "expr": "sum(rate(proxy_Propose_MakeRequestProxyNotReady{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Make Request: proxy not ready"
    },
    {
     "expr": "sum(rate(proxy_Propose_TxNotImplemented{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Make Request: proxy not implemented"
    },
    {
     "expr": "sum(rate(proxy_Propose_SchemeRequest{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Scheme Request"
    },
    {
     "expr": "sum(rate(proxy_Propose_SchemeRequestProxyNotReady{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "Scheme Request: proxy not ready"
    }
   ]
  },
  {
   "title": "DataReq: report status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(proxy_ReportStatus_OK{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(rate(proxy_ReportStatus_NotOK{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "not ok"
    },
    {
     "expr": "sum(rate(proxy_ExecTimeout{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "DataReq: received make request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(proxy_MakeRequest_ProxyAccepted{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "proxy accepted"
    },
    {
     "expr": "sum(rate(proxy_MakeRequest_WrongRequest{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "wrong request"
    },
    {
     "expr": "sum(rate(proxy_MakeRequest_EmptyAffectedSet{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "empty affected set"
    }
   ]
  },
  {
   "title": "DataReq: merge result",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(proxy_MergeResult_RequestExecComplete{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "request exec complete"
    },
    {
     "expr": "sum(rate(proxy_MergeResult_RequestExecError{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "request exec error"
    },
    {
     "expr": "sum(rate(proxy_MergeResult_MiniKQLExecComplete{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "miniKQL exec complete"
    },
    {
     "expr": "sum(rate(proxy_MergeResult_MiniKQLExecError{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "miniKQL exec error"
    },
    {
     "expr": "sum(rate(proxy_MergeResult_MiniKQLUnknownStatus{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "miniKQL unknown status"
    }
   ]
  },
  {
   "title": "DataReq: miniKQL size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(proxy_MiniKQLProgramSize{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "miniKQL program size"
    },
    {
     "expr": "sum(rate(proxy_MiniKQLParamsSize{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "miniKQL parameters size"
    }
   ]
  },
  {
   "title": "DataReq: tablets plan result",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(proxy_Plan_TxResult_Complete{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "complete"
    },
    {
     "expr": "sum(rate(proxy_Plan_TxResult_Aborted{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "aborted"
    },
    {
     "expr": "sum(rate(proxy_Plan_TxResult_ExecError{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "exec error"
    }
   ]
  },
  {
   "title": "DataReq: miniKQL resolve",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(proxy_MiniKQLResolve_SentToShard{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "sent to shard"
    },
    {
     "expr": "sum(rate(proxy_MiniKQLResolve_WrongRequest{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "wrong request"
    }
   ]
  },
  {
   "title": "DataReq: tx result",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(proxy_TxResult_Prepared{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "prepared"
    },
    {
     "expr": "sum(rate(proxy_TxResult_Complete{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "complete"
    },
    {
     "expr": "sum(rate(proxy_TxResult_TabletPrepared{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "tablet prepared"
    },
    {
     "expr": "sum(rate(proxy_TxResult_Error{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "error"
    },
    {
     "expr": "sum(rate(proxy_TxResult_Fatal{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "fatal"
    },
    {
     "expr": "sum(rate(proxy_TxResult_Aborted{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "aborted"
    }
   ]
  },
  {
   "title": "DataReq: resolve key set",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(proxy_ResolveKeySet_LegacySuccess{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "legacy success"
    },
    {
     "expr": "sum(rate(proxy_ResolveKeySet_MiniKQLSuccess{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(proxy_ResolveKeySet_Fail{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "fail"
    },
    {
     "expr": "sum(rate(proxy_ResolveKeySet_WrongRequest{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "wrong request"
    }
   ]
  },
  {
   "title": "DataReq: coordinator status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(proxy_ClientTx_Status_Planned{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "planned"
    },
    {
     "expr": "sum(rate(proxy_PrepareErrorTimeout{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "prepare error timeout"
    },
    {
     "expr": "sum(rate(proxy_ClientTx_Status_CoordinatorDeclined{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "coordinator declined"
    },
    {
     "expr": "sum(rate(proxy_ClientTx_Status_Processed{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "processed"
    },
    {
     "expr": "sum(rate(proxy_ClientTx_Status_Confirmed{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "confirmed"
    },
    {
     "expr": "sum(rate(proxy_ClientTx_Status_Accepted{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "accepted"
    }
   ]
  },
  {
   "title": "DataReq: client connected",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(proxy_ClientConnected_Ok{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(rate(proxy_ClientConnected_Error{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "DataReq: plan",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(proxy_Plan_ClientConnected{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "client connected"
    },
    {
     "expr": "sum(rate(proxy_Plan_ClientDestroyed{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "client destroyed"
    },
    {
     "expr": "sum(rate(proxy_Plan_CoordinatorDeclined{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "coordinator declined"
    }
   ]
  },
  {
   "title": "DataReq: client destroyed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(proxy_ClientDestoroyed_Ok{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(rate(proxy_ClientDestoroyed_Error{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "TxTotalTimes (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxTotalTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxPrepareTimes (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxPrepareTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxExecuteTimes (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxExecuteTimesMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxExecSpread (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxExecSpreadMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxPrepareArriveSpread (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxPrepareArriveSpreadMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxPrepareSpread (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxPrepareSpreadMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxPrepareCompleteSpread (ms)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxPrepareCompleteSpreadMs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxPrepareBuildShardPrograms (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxPrepareBuildShardProgramsUs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxPrepareResolve (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxPrepareResolveUs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxPrepareSendShardPrograms (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxPrepareSendShardProgramsUs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TxPrepareSetProgram (us)",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum by (le) (rate(proxy_TxPrepareSetProgramUs_bucket{database=\"$database\",container=\"ydb-dynamic\"}[$__rate_interval]))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}