---
# YDB restart dynamic nodes on a single host

- name: Restart the dynamic nodes on {{ dynnode_name }}
  ansible.builtin.systemd:
    state: restarted
    name: "ydbd-{{ ydb_dbname }}-{{ item.instance }}"
  throttle: 1
  delegate_to: "{{ dynnode_name }}"
  delegate_facts: true
  loop: "{{ ydb_dynnodes }}"
  any_errors_fatal: true

- name: Transfer the secrets to {{ dynnode_name }}
  copy:
    src: secret
    dest: "{{ ydb_dir }}/certs/secret"
    group: ydb
    owner: ydb
    mode: '0700'
  delegate_to: "{{ dynnode_name }}"
  delegate_facts: true
  any_errors_fatal: true

- name: Wait for the dynamic nodes to come up
  command: "{{ ydb_dir }}/home/wait_dynamic.sh {{ inventory_hostname }} {{ 2136 + item.offset }} {{ ydb_dbname }}"
  become: true
  become_user: ydb
  delegate_to: "{{ dynnode_name }}"
  delegate_facts: true
  loop: "{{ ydb_dynnodes }}"

- name: Cleanup the transferred secrets at {{ dynnode_name }}
  file: state=absent path={{ ydb_dir }}/certs/secret
  delegate_to: "{{ dynnode_name }}"
  delegate_facts: true

- name: Additional delay to settle the dynamic nodes
  ansible.builtin.pause: seconds={{ dynnode_restart_sleep_seconds }}
