storage_config_generation: 0
static_erasure: mirror-3-dc
host_configs:
- drive:
  - path: /dev/disk/by-partlabel/ydb_disk_1
    type: SSD
  host_config_id: 1

hosts:
- host: ycydb-s1
  node_id: 1
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-a'
    rack: '1'
- host: ycydb-s2
  node_id: 2
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-b'
    rack: '1'
- host: ycydb-s3
  node_id: 3
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-c'
    rack: '1'
- host: ycydb-s4
  node_id: 4
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-a'
    rack: '2'
- host: ycydb-s5
  node_id: 5
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-b'
    rack: '2'
- host: ycydb-s6
  node_id: 6
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-c'
    rack: '2'
- host: ycydb-s7
  node_id: 7
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-a'
    rack: '3'
- host: ycydb-s8
  node_id: 8
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-b'
    rack: '3'
- host: ycydb-s9
  node_id: 9
  host_config_id: 1
  walle_location:
    body: 1
    data_center: 'zone-c'
    rack: '3'

domains_config:
  domain:
  - name: Domain0
    storage_pool_types:
    - kind: ssd
      pool_config:
        box_id: 1
        erasure_species: mirror-3-dc
        kind: ssd
        pdisk_filter:
        - property:
          - type: SSD
        vdisk_kind: Default
  state_storage:
  - ring:
      node: [1, 2, 3, 4, 5, 6, 7, 8, 9]
      nto_select: 9
    ssid: 1
  security_config:
    enforce_user_token_requirement: true      # User 'root' with the empty password out of box
    monitoring_allowed_sids:
    - "root"
    - "ADMINS"
    - "DATABASE-ADMINS"
    administration_allowed_sids:
    - "root"
    - "ADMINS"
    - "DATABASE-ADMINS"
    viewer_allowed_sids:
    - "root"
    - "ADMINS"
    - "DATABASE-ADMINS"
    register_dynamic_node_allowed_sids:
    - "root@builtin" # required, does not add any real extra permissions
    - "registerNode@cert"

client_certificate_authorization:
  request_client_certificate: true
  client_certificate_definitions:
    - member_groups: ["registerNode@cert"]
      subject_terms:
      - short_name: "O"
        values: ["YDB Self-Signed Authority"]

blob_storage_config:
  service_set:
    groups:
    - erasure_species: mirror-3-dc
      rings:
      - fail_domains:
        - vdisk_locations:
          - node_id: 1
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 4
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 7
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
      - fail_domains:
        - vdisk_locations:
          - node_id: 2
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 5
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 8
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
      - fail_domains:
        - vdisk_locations:
          - node_id: 3
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 6
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1
        - vdisk_locations:
          - node_id: 9
            pdisk_category: SSD
            path: /dev/disk/by-partlabel/ydb_disk_1

channel_profile_config:
  profile:
  - channel:
    - erasure_species: mirror-3-dc
      pdisk_category: 1   # 0=ROT, 1=SSD, 2=NVME
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 1
      storage_pool_kind: ssd
    - erasure_species: mirror-3-dc
      pdisk_category: 1
      storage_pool_kind: ssd
    profile_id: 0

interconnect_config:
    start_tcp: true
    encryption_mode: OPTIONAL
    path_to_certificate_file: "/opt/ydb/certs/node.crt"
    path_to_private_key_file: "/opt/ydb/certs/node.key"
    path_to_ca_file: "/opt/ydb/certs/ca.crt"

grpc_config:
    worker_threads: 2
    workers_per_completion_queue: 1
    handlers_per_completion_queue: 1000
    grpc_proxy_count: 2
    services_enabled:
    - legacy

bootstrap_config:
  shared_cache_config: {memory_limit: '4294967296'}

feature_flags:
  check_database_access_permission: true

table_service_config:
  sql_version: 1

audit_config:
  file_backend:
    format: JSON
    file_path: "ydb-audit.log" # Relative path should be used

# Actor system config is appended to the configuration file by Ansible task.
# Provided here in the commented form for reference
#actor_system_config:
#  use_auto_config: true
#  node_type: STORAGE # STORAGE or COMPUTE
#  cpu_count: 6
