metadata:
  kind: MainConfig
  cluster: ""
  version: 6
config:
  yaml_config_enabled: true
  log_config:
    default_level: 4
allowed_labels:
  node_id:
    type: string
  host:
    type: string
  tenant:
    type: string
selector_config: []
