---
- name: ensure certs group exists
  group:
    name: certs
    system: true

- name: Create the YDB certs directory
  file:
    state: directory
    path: "{{ ydb_dir }}/certs"
    group: ydb
    owner: ydb
    mode: '0700'

- name: copy the TLS ca.crt
  copy:
    src: "{{ ydb_tls_dir }}/ca.crt"
    dest: "{{ ydb_dir }}/certs/ca.crt"
    owner: root
    group: certs
    mode: 0440

- name: copy the TLS node.crt
  copy:
    src: "{{ ydb_tls_dir }}/{{ inventory_hostname_short }}/node.crt"
    dest: "{{ ydb_dir }}/certs/node.crt"
    owner: root
    group: certs
    mode: 0440

- name: copy the TLS node.key
  copy:
    src: "{{ ydb_tls_dir }}/{{ inventory_hostname_short }}/node.key"
    dest: "{{ ydb_dir }}/certs/node.key"
    owner: root
    group: certs
    mode: 0440

- name: copy the TLS web.pem
  copy:
    src: "{{ ydb_tls_dir }}/{{ inventory_hostname_short }}/web.pem"
    dest: "{{ ydb_dir }}/certs/web.pem"
    owner: root
    group: certs
    mode: 0440
